import { describe, expect, it } from "vitest";
import { actionLabel, huntPack, investigationFromPriority, urgencyLabel } from "./operations";
import type { HuntRecord, OperationalPriority } from "../types";

const priority: OperationalPriority = {
  id: "threat-1",
  title: "Exploited gateway vulnerability",
  summary: "Active exploitation is confirmed.",
  score: 91,
  urgency: "critical",
  action_type: "patch",
  recommended_action: "Patch or isolate affected technology.",
  reasons: ["CISA KEV confirms active exploitation"],
  watchlist_matches: ["Ivanti"],
  evidence: { cves: ["CVE-2026-1000"], techniques: [], iocs: ["192.0.2.10"], ioc_count: 1 },
};

describe("operational presentation", () => {
  it("uses clear action and urgency labels", () => {
    expect(actionLabel("patch")).toBe("Patch or isolate");
    expect(actionLabel("hunt")).toBe("Begin threat hunt");
    expect(actionLabel("investigate")).toBe("Validate relevance");
    expect(actionLabel("monitor")).toBe("Monitor evidence");
    expect(urgencyLabel("critical")).toBe("Immediate");
    expect(urgencyLabel("high")).toBe("High priority");
    expect(urgencyLabel("medium")).toBe("Review");
  });

  it("creates an investigation from traceable priority evidence", () => {
    const investigation = investigationFromPriority(priority, "2026-10-08T00:00:00.000Z");
    expect(investigation).toMatchObject({
      id: "investigation-threat-1",
      sourceId: "threat-1",
      title: priority.title,
      status: "open",
      cves: ["CVE-2026-1000"],
    });
  });

  it("uses the evidence-gated package generated by the backend", () => {
    const hunt = {
      id: "hunt-1",
      entity_type: "cve",
      entity_name: "CVE-2026-1000",
      title: "Investigate CVE-2026-1000",
      status: "qualified",
      readiness_score: 90,
      confidence: "high",
      summary: "Correlated evidence",
      hypothesis: "Affected systems may show reported behavior.",
      why_qualified: [],
      report_count: 3,
      source_count: 2,
      sources: [],
      observables: [],
      techniques: [],
      telemetry: [],
      queries: [],
      false_positives: [],
      triage_steps: [],
      limitations: [],
      markdown: "# Qualified hunt\n\n## Sources\n- Source A",
    } satisfies HuntRecord;

    expect(huntPack(hunt)).toBe(hunt.markdown);
  });
});
