import { useState } from "preact/hooks";
import { ErrorState, LoadingState, PageHeader } from "../components/PageState";
import { useResource } from "../hooks/useResource";
import { api } from "../services/api";
import { actionText, formattedDate } from "../utils/format";

const regions = [
  { id: "latest", label: "Global" },
  { id: "na", label: "North America" },
  { id: "emea", label: "EMEA" },
  { id: "apac", label: "Asia Pacific" },
];

export function BriefingsView() {
  const [region, setRegion] = useState("latest");
  const resource = useResource((signal) => api.briefing(region, signal), [region]);
  return (
    <div class="view briefings-view">
      <PageHeader eyebrow="Validated narrative" title="Briefings" description="Regional intelligence digests with source-linked assessments and analyst actions." />
      <div aria-label="Briefing region" class="segmented-control" role="group">
        {regions.map((item) => <button aria-pressed={region === item.id} class={region === item.id ? "active" : ""} key={item.id} onClick={() => setRegion(item.id)} type="button">{item.label}</button>)}
      </div>
      {resource.loading && <LoadingState label="Loading briefing" />}
      {resource.error && <ErrorState message={resource.error} />}
      {resource.data && (
        <article class="briefing-document">
          <header><div><span class={`risk-label ${(resource.data.threat_level || "unknown").toLowerCase()}`}>{resource.data.threat_level || "Unclassified"}</span><span>{resource.data.reporting_window || "Current reporting window"}</span></div><h2>{resource.data.headline || "Briefing headline pending"}</h2><p>{resource.data.assessment_basis || "Assessment basis pending."}</p><time>{formattedDate(resource.data.generated_at)}</time></header>
          <section><p class="eyebrow">Situation</p><h3>What happened</h3><p>{resource.data.what_happened || "Narrative summary pending."}</p></section>
          <section><p class="eyebrow">Priorities</p><h3>What to do</h3>{resource.data.what_to_do?.length ? <ol>{resource.data.what_to_do.map((action, index) => <li key={`${index}-${actionText(action)}`}>{actionText(action)}</li>)}</ol> : <p>Validated actions are pending.</p>}</section>
          <section><p class="eyebrow">Forward look</p><h3>Outlook</h3><p>{resource.data.outlook || "No validated outlook is available."}</p></section>
          <footer><span>Generated by {resource.data.provider || "deterministic fallback"}</span><span>{resource.data.source_articles?.length || 0} cited sources</span>{resource.data.served_stale && <span class="tag tag-warning">Cached briefing</span>}</footer>
        </article>
      )}
    </div>
  );
}
